# Generated by Django 3.2.23 on 2024-01-16 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.investment'),
        ),
    ]
