# Generated by Django 3.2.23 on 2024-01-17 04:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activity_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.investment_image_file_path),
        ),
    ]
